"use client";

import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { byId, catalog, price, readCart, writeCart } from "../../lib/catalog";

export default function ProductPage() {
  const { id } = useParams<{id:string}>(); const router = useRouter(); const product = byId(id); const [quantity, setQuantity] = useState(1); const [added, setAdded] = useState(false);
  if (!product) return <main className="routePage notFound"><h1>Produit introuvable.</h1><a className="darkButton" href="/">Retour à la boutique</a></main>;
  const add = (go = false) => { writeCart([...readCart(), ...Array.from({length:quantity}, () => product)]); go ? router.push("/panier") : setAdded(true); };
  return <main className="routePage productPage"><div className="routeHeader"><button onClick={() => router.back()}>← Retour</button><a className="wordmark" href="/">nexa<span>•</span></a><a className="routeBag" href="/panier"><span className="bagIcon" /></a></div><div className="breadcrumbs"><a href="/">Accueil</a><span>/</span><a href="/#produits">{product.category}</a><span>/</span><b>{product.name}</b></div><section className="pdpGrid"><div className="pdpImage"><img src={product.image} alt={product.name}/></div><div className="pdpInfo"><p className="kicker">{product.brand} · {product.category}</p><h1>{product.name}</h1><p className="pdpRating">★★★★★ <b>4.8 / 5</b> · 24 avis</p><div className="pdpPrice"><strong>{price(product.price)}</strong>{product.oldPrice && <del>{price(product.oldPrice)}</del>}</div><p className="pdpIntro">{product.description}</p><div className="pdpChoice"><span>Couleur <b>Midnight</b></span><div><button className="colorDot active"/><button className="colorDot soft"/><button className="colorDot blue"/></div></div><div className="pdpActions"><div className="quantity"><button disabled={quantity === 1} onClick={() => setQuantity(quantity-1)}>−</button><b>{quantity}</b><button onClick={() => setQuantity(quantity+1)}>+</button></div><button className="primaryButton addProduct" onClick={() => add()}>Ajouter au panier <span>→</span></button></div><button className="buyNow" onClick={() => add(true)}>Acheter maintenant</button><div className="pdpDelivery"><p><b>Livraison offerte dès 199 DT</b><small>Expédition en Tunisie sous 24–48 h.</small></p><p><b>Retours simplifiés</b><small>14 jours pour changer d’avis.</small></p></div></div></section><section className="pdpDetails"><details open><summary>Description <span>+</span></summary><p>{product.description}</p></details><details><summary>Caractéristiques <span>+</span></summary><p>Garantie 12 mois · Livraison partout en Tunisie · Paiement sécurisé.</p></details><details><summary>Livraison & retours <span>+</span></summary><p>Livraison offerte dès 199 DT. Retours acceptés durant 14 jours.</p></details></section><section className="similar section"><p className="kicker">À découvrir aussi</p><h2>Complétez votre sélection.</h2><div className="productRail">{catalog.filter(item => item.id !== product.id).slice(0,4).map(item => <a className="simpleProduct" href={`/produit/${item.id}`} key={item.id}><img src={item.image} alt={item.name}/><small>{item.brand}</small><b>{item.name}</b><strong>{price(item.price)}</strong></a>)}</div></section>{added && <div className="toast">✓ <span>Ajouté au panier.</span><a href="/panier">Voir le panier</a></div>}</main>;
}
