"use client";

import { useEffect, useState } from "react";
import { price, readCart, type CatalogProduct, writeCart } from "../lib/catalog";

export default function CartPage() {
  const [cart, setCart] = useState<CatalogProduct[]>([]); useEffect(() => setCart(readCart()), []); const total = cart.reduce((sum,item) => sum+item.price,0); const save = (items:CatalogProduct[]) => {setCart(items); writeCart(items);};
  return <main className="routePage cartPage"><div className="routeHeader"><a href="/">← Continuer mes achats</a><a className="wordmark" href="/">nexa<span>•</span></a><span/></div><div className="checkoutSteps"><span className="active">1 · Panier</span><i/><span>2 · Livraison</span><i/><span>3 · Paiement</span></div><section className="cartPageGrid"><div><p className="kicker">Votre sélection</p><h1>Votre panier <small>({cart.length})</small></h1>{cart.length ? <div className="cartPageItems">{cart.map((item,index) => <article key={`${item.id}-${index}`}><img src={item.image} alt={item.name}/><div><small>{item.brand}</small><h2>{item.name}</h2><b>{price(item.price)}</b><button onClick={() => save(cart.filter((_,i) => i !== index))}>Retirer</button></div><button className="removeItem" onClick={() => save(cart.filter((_,i) => i !== index))}>×</button></article>)}</div> : <div className="cartEmpty"><span className="bagIcon"/><h2>Votre panier est vide.</h2><p>Parcourez nos essentiels et créez votre sélection.</p><a className="darkButton" href="/#produits">Découvrir les produits</a></div>}</div><aside className="orderSummary"><p className="kicker">Récapitulatif</p><p>Sous-total <b>{price(total)}</b></p><p>Livraison <b>{total >= 199 ? "Offerte" : "À calculer"}</b></p><h2>Total <b>{price(total)}</b></h2>{cart.length ? <a className="primaryButton" href="/checkout">Finaliser la commande <span>→</span></a> : <button className="primaryButton" disabled>Finaliser la commande</button>}<small>Vous choisirez le paiement à la prochaine étape.</small></aside></section></main>;
}
